#!/bin/bash

if [[ $# == 0 ]]; then
    echo "Usage:";
    echo "Install SCIST Linux Challenge RPG:  ./snippet install"
    echo "Start SCIST Linux Challenge RPG:    ./snippet start"
    echo "Stop SCIST Linux Challenge RPG:     ./snippet stop"
    exit 0
fi

architecture=$(uname -m)

if [[ $1 == "install" ]]; then
    if [ -f "docker-compose.yml" ]; then
        echo "SCIST Linux Challenge RPG is already installed."
        exit 0
    fi
    echo "version: '2'" > docker-compose.yml
    echo "services:" >> docker-compose.yml
    echo "    challenge_box:" >> docker-compose.yml
    echo "        container_name: challenge_box" >> docker-compose.yml
    echo "        image: curiouslucifer/scist_linux_challenge_rpg:1.0-challenge_box-$architecture" >> docker-compose.yml
    echo "    ssh_service:" >> docker-compose.yml
    echo "        container_name: ssh_service" >> docker-compose.yml
    echo "        image: curiouslucifer/scist_linux_challenge_rpg:1.0-ssh_service-$architecture" >> docker-compose.yml
    echo "    web_service:" >> docker-compose.yml
    echo "        container_name: web_service" >> docker-compose.yml
    echo "        image: curiouslucifer/scist_linux_challenge_rpg:1.0-web_service-$architecture" >> docker-compose.yml
elif [[ $1 == "start" ]]; then
    docker compose up -d
    docker exec -it challenge_box bash
elif [[ $1 == "stop" ]]; then
    docker compose down
fi