#!/bin/bash

version=2.0

if [[ $# == 0 ]]; then
    echo "Usage :";
    echo "Install SCIST Linux Challenge RPG : ./snippet install"
    echo "Start SCIST Linux Challenge RPG   : ./snippet start"
    echo "Stop SCIST Linux Challenge RPG    : ./snippet stop"
    echo "Remove SCIST Linux Challenge RPG  : ./snippet remove"
    exit 0
fi

if [[ $1 == "install" ]]; then
    if ! command -v docker &> /dev/null; then
        sudo apt update && sudo apt upgrade -y
        sudo apt install curl -y
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
    fi
    if [ -f "docker-compose.yml" ]; then
        echo "SCIST Linux Challenge RPG is already installed."
        exit 0
    fi
    docker pull curiouslucifer/scist_linux_challenge_rpg:$version-challenge_box
    docker pull curiouslucifer/scist_linux_challenge_rpg:$version-ssh_service
    docker pull curiouslucifer/scist_linux_challenge_rpg:$version-web_service
    wget https://linux.ctf.scist.org/files/2d0667f5e7a6d40cfa6cda3ce864e655/docker-compose.yml
elif [[ $1 == "start" ]]; then
    docker compose up -d
    exec docker exec -it challenge_box bash
elif [[ $1 == "stop" ]]; then
    docker compose down
elif [[ $1 == "remove" ]]; then
    docker rmi curiouslucifer/scist_linux_challenge_rpg:2.0-web_service curiouslucifer/scist_linux_challenge_rpg:2.0-ssh_service curiouslucifer/scist_linux_challenge_rpg:2.0-challenge_box
    rm -r ~/SCIST_Linux_Challenge
fi